version: 2.1
executors:
  java-executor:
    docker:
      - image: circleci/openjdk:17-jdk
workflows:
  build-and-deploy:
    jobs:
      - build-docker
jobs:
  build-docker:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            sudo apt-get update
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Build and push Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t ${DOCKERHUB_USERNAME}/${DOCKER_IMAGE_NAME}:latest .
            docker push ${DOCKERHUB_USERNAME}/${DOCKER_IMAGE_NAME}:latest
