version: 2.1
workflows:
  build-and-deploy:
    jobs:
      - build-docker:
          filters:
            branches:
              only:
                - main
                - dev
      - deploy-to-aws:
          requires:
            - build-docker
          filters:
            branches:
              only:
                - main
jobs:
  build-docker:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Check Dockerfile
          command: cat Dockerfile
      - run:
          name: Install Docker Compose
          command: |
            sudo apt-get update
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Build and push Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build \
              --build-arg DB_USERNAME="$DB_USERNAME" \
              --build-arg DB_PASSWORD="$DB_PASSWORD" \
              --build-arg DB_HOST="$DB_HOST" \
              --build-arg DB_DATABASE="$DB_DATABASE" \
              --build-arg TEST_USERNAME="$TEST_USERNAME" \
              --build-arg TEST_PASSWORD="$TEST_PASSWORD" \
              --build-arg LIVIZ_JWT_SECRET_KEY="$LIVIZ_JWT_SECRET_KEY" \
              -t ${DOCKERHUB_USERNAME}/${DOCKER_IMAGE_NAME}:latest .
            docker push ${DOCKERHUB_USERNAME}/${DOCKER_IMAGE_NAME}:latest
  deploy-to-aws:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "${SSH_FINGERPRINT}"
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y rsync
            sudo apt-get install -y python3-pip
            sudo pip3 install awscli
      - run:
          name: Install Docker on AWS EC2
          command: |
            rsync -av -e "ssh -o StrictHostKeyChecking=no" --delete --exclude '.*' ./ $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH
            ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "cd $REMOTE_PATH \
            && sudo apt-get update \
            && sudo apt-get install ca-certificates curl gnupg \
            && sudo mkdir -m 0755 -p /etc/apt/keyrings \
            && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg \
            && echo \
              "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
                "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
                sudo tee /etc/apt/sources.list.d/docker.list > /dev/null \
            && sudo chmod a+r /etc/apt/keyrings/docker.gpg \
            && sudo apt-get update \
            && sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin \
            && sudo docker run hello-world
      - run:
          name: Deploy to AWS EC2
          command: |
            rsync -av -e "ssh -o StrictHostKeyChecking=no" --delete --exclude '.*' ./ $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH
            ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "cd $REMOTE_PATH \
              && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin \
              && docker pull $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:latest \
              && (docker stop $DOCKER_CONTAINER_NAME && docker rm $DOCKER_CONTAINER_NAME) 2>/dev/null || true  \
              && docker run -d \
                  --name $DOCKER_CONTAINER_NAME \
                  -p 8081:8081 \
                  $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:latest"
